// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuRFtjckpsDE86ep14tSwhw_WcOMxi8ng',
    appId: '1:496037373360:web:39511f7d3d5e46f485a275',
    messagingSenderId: '496037373360',
    projectId: 'elimupath-fe1fb',
    authDomain: 'elimupath-fe1fb.firebaseapp.com',
    storageBucket: 'elimupath-fe1fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyjNX1J4tKB9JQnYWDRz3M2HBpHQz-S_w',
    appId: '1:496037373360:android:2ce399f11bad0f7685a275',
    messagingSenderId: '496037373360',
    projectId: 'elimupath-fe1fb',
    storageBucket: 'elimupath-fe1fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC4lMlPTWujbGmqR_BUOK_ZWWBnihOH-A',
    appId: '1:496037373360:ios:e42a77147a10ad2f85a275',
    messagingSenderId: '496037373360',
    projectId: 'elimupath-fe1fb',
    storageBucket: 'elimupath-fe1fb.firebasestorage.app',
    iosBundleId: 'com.example.elimupath',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC4lMlPTWujbGmqR_BUOK_ZWWBnihOH-A',
    appId: '1:496037373360:ios:e42a77147a10ad2f85a275',
    messagingSenderId: '496037373360',
    projectId: 'elimupath-fe1fb',
    storageBucket: 'elimupath-fe1fb.firebasestorage.app',
    iosBundleId: 'com.example.elimupath',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuRFtjckpsDE86ep14tSwhw_WcOMxi8ng',
    appId: '1:496037373360:web:55af697a530dc0c185a275',
    messagingSenderId: '496037373360',
    projectId: 'elimupath-fe1fb',
    authDomain: 'elimupath-fe1fb.firebaseapp.com',
    storageBucket: 'elimupath-fe1fb.firebasestorage.app',
  );
}
