import 'package:cloud_firestore/cloud_firestore.dart';

Future<void> seedRwandanSchools() async {
  final firestore = FirebaseFirestore.instance;
  final schoolsCollection = firestore.collection('schools');

  // Check if schools already exist so we don't duplicate them
  final snapshot = await schoolsCollection.limit(1).get();
  if (snapshot.docs.isNotEmpty) {
    print('✅ Schools are already seeded. Skipping...');
    return;
  }

  print('⏳ Seeding 15 Rwandan schools into Firestore...');

  final List<Map<String, dynamic>> schoolsToSeed = [
    {
      'name': 'Lycée de Kigali (LDK)',
      'district': 'Nyarugenge',
      'type': 'day',
      'gender': 'mixed',
      'combinations': ['MPC', 'MCB', 'PCM', 'MEG'],
      'feesPerTerm': 65000.0,
      'admissionStatus': true,
      'availableSlots': 120,
      'performanceIndex': 9.2,
      'facilities': ['Library', 'Computer Lab', 'Basketball Court', 'Science Lab'],
      'photos': [],
      'verified': true,
      'adminId': 'admin_dummy_1',
      'contact': '+250788000001',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'name': 'FAWE Girls\' School Gisozi',
      'district': 'Gasabo',
      'type': 'boarding',
      'gender': 'girls',
      'combinations': ['MCB', 'PCB', 'MPC', 'MEG'],
      'feesPerTerm': 95000.0,
      'admissionStatus': true,
      'availableSlots': 80,
      'performanceIndex': 9.5,
      'facilities': ['Dormitories', 'Science Lab', 'Library', 'Dining Hall'],
      'photos': [],
      'verified': true,
      'adminId': 'admin_dummy_2',
      'contact': '+250788000002',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'name': 'Groupe Scolaire Officiel de Butare (GSOB)',
      'district': 'Huye',
      'type': 'boarding',
      'gender': 'mixed',
      'combinations': ['MPC', 'PCB', 'MCB', 'HEG', 'MEG'],
      'feesPerTerm': 85000.0,
      'admissionStatus': true,
      'availableSlots': 150,
      'performanceIndex': 9.0,
      'facilities': ['Football Pitch', 'Library', 'Dormitories'],
      'photos': [],
      'verified': true,
      'adminId': 'admin_dummy_3',
      'contact': '+250788000003',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'name': 'Gashora Girls Academy',
      'district': 'Bugesera',
      'type': 'boarding',
      'gender': 'girls',
      'combinations': ['MPC', 'MCB', 'PCB'],
      'feesPerTerm': 300000.0,
      'admissionStatus': true,
      'availableSlots': 45,
      'performanceIndex': 9.8,
      'facilities': ['Modern Labs', 'Smart Classrooms', 'Sports Complex'],
      'photos': [],
      'verified': true,
      'adminId': 'admin_dummy_4',
      'contact': '+250788000004',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'name': 'Petit Séminaire Ndera',
      'district': 'Gasabo',
      'type': 'boarding',
      'gender': 'boys',
      'combinations': ['MPC', 'MCB', 'HEG', 'LEG'],
      'feesPerTerm': 90000.0,
      'admissionStatus': false,
      'availableSlots': 0,
      'performanceIndex': 9.3,
      'facilities': ['Chapel', 'Library', 'Football Field'],
      'photos': [],
      'verified': true,
      'adminId': 'admin_dummy_5',
      'contact': '+250788000005',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'name': 'Riviera High School',
      'district': 'Gasabo',
      'type': 'boarding',
      'gender': 'mixed',
      'combinations': ['MPC', 'MCB', 'HEG', 'MEG'],
      'feesPerTerm': 450000.0,
      'admissionStatus': true,
      'availableSlots': 60,
      'performanceIndex': 8.9,
      'facilities': ['Swimming Pool', 'Tennis Court', 'Modern Dorms'],
      'photos': [],
      'verified': true,
      'adminId': 'admin_dummy_6',
      'contact': '+250788000006',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'name': 'Ecole des Sciences Byimana',
      'district': 'Ruhango',
      'type': 'boarding',
      'gender': 'mixed',
      'combinations': ['MPC', 'MCB', 'PCB'],
      'feesPerTerm': 80000.0,
      'admissionStatus': true,
      'availableSlots': 100,
      'performanceIndex': 9.4,
      'facilities': ['Advanced Science Labs', 'Library', 'Dorms'],
      'photos': [],
      'verified': true,
      'adminId': 'admin_dummy_7',
      'contact': '+250788000007',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'name': 'Maranyundo Girls School',
      'district': 'Bugesera',
      'type': 'boarding',
      'gender': 'girls',
      'combinations': ['MPC', 'MCB', 'PCB', 'MEG'],
      'feesPerTerm': 120000.0,
      'admissionStatus': true,
      'availableSlots': 55,
      'performanceIndex': 9.6,
      'facilities': ['Tech Hub', 'Library', 'Cafeteria'],
      'photos': [],
      'verified': true,
      'adminId': 'admin_dummy_8',
      'contact': '+250788000008',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'name': 'King David Academy',
      'district': 'Kicukiro',
      'type': 'day',
      'gender': 'mixed',
      'combinations': ['HEG', 'LEG', 'MEG', 'MPC'],
      'feesPerTerm': 70000.0,
      'admissionStatus': true,
      'availableSlots': 200,
      'performanceIndex': 8.5,
      'facilities': ['Computer Lab', 'Playground'],
      'photos': [],
      'verified': true,
      'adminId': 'admin_dummy_9',
      'contact': '+250788000009',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'name': 'Nu-Vision High School',
      'district': 'Gasabo',
      'type': 'boarding',
      'gender': 'mixed',
      'combinations': ['MPC', 'MCB', 'PCB', 'MEG', 'HEG'],
      'feesPerTerm': 350000.0,
      'admissionStatus': true,
      'availableSlots': 90,
      'performanceIndex': 9.1,
      'facilities': ['Sports Arena', 'Science Lab', 'Library'],
      'photos': [],
      'verified': true,
      'adminId': 'admin_dummy_10',
      'contact': '+250788000010',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'name': 'Sonrise High School',
      'district': 'Musanze',
      'type': 'boarding',
      'gender': 'mixed',
      'combinations': ['MPC', 'MCB', 'PCB', 'HEG'],
      'feesPerTerm': 150000.0,
      'admissionStatus': true,
      'availableSlots': 75,
      'performanceIndex': 8.8,
      'facilities': ['Dormitories', 'Library', 'Chapel'],
      'photos': [],
      'verified': true,
      'adminId': 'admin_dummy_11',
      'contact': '+250788000011',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'name': 'College Saint Andre',
      'district': 'Nyarugenge',
      'type': 'day',
      'gender': 'mixed',
      'combinations': ['MPC', 'MCB', 'MEG', 'HEG'],
      'feesPerTerm': 60000.0,
      'admissionStatus': false,
      'availableSlots': 0,
      'performanceIndex': 8.7,
      'facilities': ['Basketball Court', 'Science Lab'],
      'photos': [],
      'verified': true,
      'adminId': 'admin_dummy_12',
      'contact': '+250788000012',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'name': 'Kagarama Secondary School',
      'district': 'Kicukiro',
      'type': 'day',
      'gender': 'mixed',
      'combinations': ['MPC', 'MCB', 'HEG', 'MEG'],
      'feesPerTerm': 55000.0,
      'admissionStatus': true,
      'availableSlots': 130,
      'performanceIndex': 8.6,
      'facilities': ['Library', 'Football Pitch'],
      'photos': [],
      'verified': true,
      'adminId': 'admin_dummy_13',
      'contact': '+250788000013',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'name': 'APE Rugunga',
      'district': 'Nyarugenge',
      'type': 'day',
      'gender': 'mixed',
      'combinations': ['HEG', 'LEG', 'MEG'],
      'feesPerTerm': 50000.0,
      'admissionStatus': true,
      'availableSlots': 85,
      'performanceIndex': 8.2,
      'facilities': ['Computer Lab'],
      'photos': [],
      'verified': true,
      'adminId': 'admin_dummy_14',
      'contact': '+250788000014',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'name': 'Cornerstone Leadership Academy',
      'district': 'Rwamagana',
      'type': 'boarding',
      'gender': 'mixed',
      'combinations': ['MPC', 'MCB', 'PCB'],
      'feesPerTerm': 100000.0,
      'admissionStatus': true,
      'availableSlots': 40,
      'performanceIndex': 9.7,
      'facilities': ['Leadership Center', 'Library', 'Dorms'],
      'photos': [],
      'verified': true,
      'adminId': 'admin_dummy_15',
      'contact': '+250788000015',
      'createdAt': FieldValue.serverTimestamp(),
    },
  ];

  for (var school in schoolsToSeed) {
    await schoolsCollection.add(school);
  }

  print('✅ Successfully seeded 15 schools into Firestore!');
}
